### ISSUE TITLE
Upgrade playground to integrate simulator

### ISSUE THREAD

**Issue by SlnPons** [massalabs/massa-sc-playground#42]
**Context**
Inno team developed a playground accessible in web2 to facilitate the adoption and to optimise the time we had in front of us to enable users to build SC on Massa.
Now, we want to integrate and improve this work into Thyra so that we add new product to Thyra while we improve the existing playground. Adding the simulator to existing playground is what we'll do here.

**Needs**
To add the simulator functionality into existing playground

**User flow**
User installs and launch Thyra 
User sees a page named 'SC Playground'
User clicks on it and can click on simulate
User sees a selection windows to select specific file (which format?) and click on OK button 
User sees the result of the simulation displayed on the Playground front-end

**How to**

- [ ] Adding simulate button
- [ ] Process to send files to playground plug-in
- [ ] Get Trace.json  & Leddger.json files from simulator
- [ ] Display relevant data from files in console
- [ ] Adding process to check if Playground (backend) plug-in is available

**Comment by 0xMazout** [comment]
Pull Request text : 
Some limitations :
- Connection url are Hardcoded 
- Files url are not very relevant 

At this moment according with PM. We don't need to spend more time on this.
Process is working : Uploading Config file, Send it to Playground Plugin API , Receive Two files

Needs : 
The model config file imported in the repo (execution_config.json) should be respected  
The playground Plugin API is needed to launch simulator and handle requests

To test : 
Clone Playground plugin API , Run it 
Run npx http-server on playground
Upload config file 
Simulate
Verify JSON file on urls or In the Playground plugin API repo

Links : 
API PLUGIN : https://github.com/massalabs/thyra-playground-plugin
